# Global Baseline: If it isn't explicitly allowed, it's blocked.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {} # Targets ALL pods in namespace
  policyTypes:
    - Ingress
    - Egress